# Use imagem leve do Node
FROM node:20-alpine

# Define diretório
WORKDIR /app

# Copia arquivos de dependência
COPY package.json package-lock.json* ./

# Instala dependências
RUN npm install --legacy-peer-deps

# Copia o código fonte
COPY . .

# Faz o build de produção do Next.js
ENV NEXT_TELEMETRY_DISABLED=1
ENV BACKEND_INTERNAL_URL=http://backend:8000
RUN npm run build

# Expõe a porta 3000
EXPOSE 3000

# Inicia em modo produção
CMD ["npm", "run", "start"]
