import type { Meta, StoryObj } from '@storybook/nextjs';
import { RetentionChart } from '../app/components/oracle/RetentionChart';

const meta: Meta<typeof RetentionChart> = {
    title: 'App/Features/Oracle/RetentionChart',
    component: RetentionChart,
    tags: ['autodocs'],
    parameters: {
        layout: 'padded',
        backgrounds: { default: 'dark' },
    },
    decorators: [
        (Story) => (
            <div className="w-[600px]">
                <Story />
            </div>
        ),
    ],
};

export default meta;

const generateCurve = (decay: number) => Array.from({ length: 60 }, (_, i) => ({
    second: i,
    retention_rate: Math.max(0, 100 * Math.exp(-decay * i) + (Math.random() * 2)),
}));

export const StrongRetention = {
    args: {
        data: generateCurve(0.01), // Slow decay
    },
};

export const WeakRetention = {
    args: {
        data: generateCurve(0.1), // Fast decay
    },
};

export const AutoGenerated = {
    args: {
        data: [], // Component handles empty data with internal mock
    },
};

